export const LOGO_LINK =
  "https://www.creativehatti.com/wp-content/uploads/2021/04/Food-Delivery-Logo-Template-18-small.jpg";

export const CARD_API = [
  {
    id: 1,
    resName: "Dwaraka",
    famousItems: ["Paneer Butter Masala", "Veg Pulao", "Butter Naan"],
    rating: 4.3,
    price: 220,
    estimatedDelivery: "35 mins",
    isPromoted:true,
    image:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRl7aUsEBwkp3KgL0KN-tDbMT_SWQ8oQvHb7A&s",
  },
  {
    id: 2,
    resName: "KFC",
    famousItems: ["Zinger Burger", "Popcorn Chicken", "Hot Wings"],
    rating: 4.1,
    price: 160,
    estimatedDelivery: "30 mins",
    isPromoted:false,
    image:"https://content.jdmagicbox.com/v2/comp/chennai/m5/044pxx44.xx44.200602172602.w6m5/catalogue/kfc-periyar-nagar-jawahar-nagar-chennai-fast-food-weiayifzt2.jpg"
  },
  {
    id: 3,
    resName: "Domino's",
    famousItems: ["Veg Extravaganza Pizza", "Peppy Paneer Pizza", "Garlic Breadsticks"],
    rating: 4.2,
    price: 350,
    estimatedDelivery: "28 mins",
    isPromoted:false,
    image:
      "https://www.dominos.co.in/store-location/img/vegpizza.jpg",
  },
  {
    id: 4,
    resName: "McDonald's",
    famousItems: ["McAloo Tikki", "McVeggie Burger", "Fries"],
    rating: 4.0,
    price: 80,
    estimatedDelivery: "25 mins",
      isPromoted:true,
    image:"https://images.pexels.com/photos/4109268/pexels-photo-4109268.jpeg?cs=srgb&dl=pexels-polina-tankilevitch-4109268.jpg&fm=jpg"
  },
  {
    id: 5,
    resName: "Burger King",
    famousItems: ["Whopper", "Veggie Burger", "Cheesy Fries"],
    rating: 3.9,
    price: 190,
    estimatedDelivery: "33 mins",
      isPromoted:false,
    image:"https://b.zmtcdn.com/data/pictures/chains/1/49781/5f22edaa3391108ad75776b4cbce296e.jpg"
  },
  {
    id: 6,
    resName: "Pizza Hut",
    famousItems: ["Cheese Garlic Bread", "Veggie Supreme Pizza", "Tandoori Paneer Pizza"],
    rating: 4.1,
    price: 140,
    estimatedDelivery: "27 mins",
      isPromoted:false,
    image:"https://www.yum.com/wps/wcm/connect/yumbrands/77ac5d27-1357-4792-9953-54b11f5ae7dd/yum-com-24-product-PH.jpg?MOD=AJPERES&CACHEID=ROOTWORKSPACE.Z18_5QC4HBC039RJ406SQH4UBH3695-77ac5d27-1357-4792-9953-54b11f5ae7dd-oXSxcXb"
  },
  {
    id: 7,
    resName: "Subway",
    famousItems: ["Veggie Delight Sub", "Paneer Tikka Sub", "Aloo Patty Sub"],
    rating: 4.2,
    price: 180,
    estimatedDelivery: "30 mins",
      isPromoted:true,
    image:
  "https://content3.jdmagicbox.com/comp/def_content/subway/subway-1-subway-1-1g63c.jpg"  },
  {
    id: 8,
    resName: "Haldiram's",
    famousItems: ["Chole Bhature", "Rajma Chawal", "Dahi Bhalla"],
    rating: 4.4,
    price: 120,
    estimatedDelivery: "32 mins",
      isPromoted:true,
    image:
"https://content.jdmagicbox.com/v2/comp/palghar/y9/022pxx22.xx22.221223112035.f3y9/catalogue/haldiram-s-restaurant-virar-west-palghar-restaurants-tv12uyg0lt-250.jpg"  },
  {
    id: 9,
    resName: "Bikanervala",
    famousItems: ["Raj Kachori", "Aloo Tikki", "Pav Bhaji"],
    rating: 4.5,
    price: 110,
    estimatedDelivery: "29 mins",
      isPromoted:false,
    image:
"https://content.jdmagicbox.com/v2/comp/thane/l1/022pxx22.xx22.220811112540.n6l1/catalogue/bikanervala-thane-west-thane-sweet-shops-cxiehkcbcz.jpg"  },
  {
    id: 10,
    resName: "Wow! Momo",
    famousItems: ["Fried Veg Momo", "Tandoori Momos", "Chocolate Momo"],
    rating: 4.0,
    price: 130,
    estimatedDelivery: "40 mins",
      isPromoted:true,
    image:
"https://chompslurrpburp.files.wordpress.com/2017/02/dsc_0664.jpg"  },
  {
    id: 11,
    resName: "Faasos",
    famousItems: ["Paneer Signature Wrap", "Cheese Melt Wrap", "Royal Falafel Wrap"],
    rating: 4.1,
    price: 160,
    estimatedDelivery: "22 mins",
      isPromoted:false,
    image:
"https://b.zmtcdn.com/data/pictures/chains/0/37750/5fe78176d3acf65c617ceddeac7ffb28.jpg?fit=around|960:500&crop=960:500;*,*"  },
  {
    id: 12,
    resName: "Behrouz Biryani",
    famousItems: ["Veg Biryani", "Paneer Subz Biryani", "Noorani Kebab"],
    rating: 4.3,
    price: 250,
    estimatedDelivery: "38 mins",
      isPromoted:false,
    image:
"https://www.indianhealthyrecipes.com/wp-content/uploads/2019/04/veg-biryani-recipe.jpg"  },
  {
    id: 13,
    resName: "LunchBox",
    famousItems: ["Deluxe Thali", "Paneer Masala", "Dum Aloo"],
    rating: 4.0,
    price: 200,
    estimatedDelivery: "24 mins",
      isPromoted:true,
    image:
"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSQRQMKHs5qBBmBwVN6e7UTPlt3PpK2c6T8XA&s"  },
  {
    id: 14,
    resName: "Oven Story Pizza",
    famousItems: ["Farmhouse Pizza", "Veg Loaded Pizza", "Cheesy Garlic Bread"],
    rating: 3.8,
    price: 300,
    estimatedDelivery: "34 mins",
      isPromoted:false,
    image:
"https://www.ambitiouskitchen.com/wp-content/uploads/2023/02/Garlic-Bread-4.jpg"  },
  {
    id: 15,
    resName: "Sweet Truth",
    famousItems: ["Chocolate Cake Jar", "Truffle Pastry", "Red Velvet Jar"],
    rating: 4.4,
    price: 150,
    estimatedDelivery: "20 mins",
      isPromoted:true,
    image:
"https://static01.nyt.com/images/2024/06/04/multimedia/Red-Velvet-Cake-twcf/Red-Velvet-Cake-twcf-mediumSquareAt3X.jpg"  },
  {
    id: 16,
    resName: "Cafe Coffee Day",
    famousItems: ["Cappuccino", "Cafe Latte", "Brownie Frappe"],
    rating: 4.2,
    price: 120,
    estimatedDelivery: "19 mins",
      isPromoted:true,
    image:
"https://upload.wikimedia.org/wikipedia/commons/thumb/7/70/Cappuccino_in_original.jpg/960px-Cappuccino_in_original.jpg"  },
  {
    id: 17,
    resName: "Chaayos",
    famousItems: ["Kulhad Chai", "Bun Maska", "Paneer Loaded Open Paratha"],
    rating: 4.3,
    price: 60,
    estimatedDelivery: "14 mins",
      isPromoted:true,
    image:
"https://carameltintedlife.com/wp-content/uploads/2021/01/Masala-Chai-.jpg"  },
  {
    id: 18,
    resName: "The Belgian Waffle",
    famousItems: ["Strawberry Waffle", "Nutella Waffle", "Chocolate Overload Waffle"],
    rating: 4.6,
    price: 170,
    estimatedDelivery: "37 mins",
    isPromoted:false,
    image:
"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTZ-F2702IzB9lyZoDkkRby2fZGb33qrExvoQ&s"  },
  {
    id: 19,
    resName: "Giani's",
    famousItems: ["Hot Chocolate Fudge", "Ferrero Rocher Sundae", "Raspberry Blast"],
    rating: 4.5,
    price: 130,
    estimatedDelivery: "29 mins",
      isPromoted:false,
    image:
"https://bakingamoment.com/wp-content/uploads/2024/12/IMG_4427-fudge-recipe-1200px.jpg"  },
  {
    id: 20,
    resName: "Rolls Mania",
    famousItems: ["Cheese Paneer Roll", "Aloo Cheese Roll", "Double Egg Roll"],
    rating: 4.1,
    price: 140,
    estimatedDelivery: "22 mins",
     isPromoted:false,
    image:
"https://www.rollsmania.com/assets/images/menu-item/burger-promo.webp"  },
];

export const RESTAURANT_INFO = [
  {
    resId: 1,
    resName: "Dwaraka",
    address: "MG Road, Bengaluru",
    rating: 4.3,
    menu: [
      { itemId: 1, itemName: "Paneer Butter Masala", price: 180 },
      { itemId: 2, itemName: "Ghee Roast Dosa", price: 90 },
      { itemId: 3, itemName: "South Indian Thali", price: 200 },
      { itemId: 4, itemName: "Masala Dosa", price: 85 },
      { itemId: 5, itemName: "Idli Sambar", price: 60 },
      { itemId: 6, itemName: "Vada", price: 35 },
      { itemId: 7, itemName: "Onion Uttapam", price: 95 },
      { itemId: 8, itemName: "Set Dosa", price: 80 },
      { itemId: 9, itemName: "Rava Kesari", price: 55 },
      { itemId: 10, itemName: "Bisibele Bath", price: 100 },
      { itemId: 11, itemName: "Curd Rice", price: 60 },
      { itemId: 12, itemName: "Lemon Rice", price: 70 },
      { itemId: 13, itemName: "Poori Sagu", price: 80 },
      { itemId: 14, itemName: "Filter Coffee", price: 45 },
      { itemId: 15, itemName: "Mysore Pak", price: 50 },
    ],
  },
  {
    resId: 2,
    resName: "KFC",
    address: "Brigade Road, Bengaluru",
    rating: 4.1,
    menu: [
      { itemId: 16, itemName: "Zinger Burger", price: 160 },
      { itemId: 17, itemName: "Chicken Popcorn", price: 120 },
      { itemId: 18, itemName: "Krusher", price: 90 },
      { itemId: 19, itemName: "Hot Wings", price: 130 },
      { itemId: 20, itemName: "Chicken Strips", price: 110 },
      { itemId: 21, itemName: "Chicken Bucket", price: 420 },
      { itemId: 22, itemName: "Smoky Grilled Chicken", price: 170 },
      { itemId: 23, itemName: "Peri Peri Chicken", price: 185 },
      { itemId: 24, itemName: "Classic Chicken Roll", price: 100 },
      { itemId: 25, itemName: "Veg Strips", price: 80 },
      { itemId: 26, itemName: "Veg Zinger Burger", price: 115 },
      { itemId: 27, itemName: "Potato Krisper Burger", price: 69 },
      { itemId: 28, itemName: "Tandoori Zinger Burger", price: 175 },
      { itemId: 29, itemName: "Chocolate Lava Cup", price: 105 },
      { itemId: 30, itemName: "Pepsi", price: 60 },
    ],
  },
  {
    resId: 3,
    resName: "Domino",
    address: "JP Nagar, Bengaluru",
    rating: 4.0,
    menu: [
      { itemId: 31, itemName: "Margherita Pizza", price: 199 },
      { itemId: 32, itemName: "Peppy Paneer", price: 299 },
      { itemId: 33, itemName: "Garlic Bread", price: 129 },
      { itemId: 34, itemName: "Farmhouse Pizza", price: 349 },
      { itemId: 35, itemName: "Chicken Fiesta", price: 359 },
      { itemId: 36, itemName: "Mexican Green Wave", price: 259 },
      { itemId: 37, itemName: "Veggie Paradise", price: 269 },
      { itemId: 38, itemName: "Cheese n Corn", price: 229 },
      { itemId: 39, itemName: "Cheese Burst Pizza", price: 299 },
      { itemId: 40, itemName: "Butterscotch Mousse", price: 99 },
      { itemId: 41, itemName: "Paneer Makhni", price: 319 },
      { itemId: 42, itemName: "Choco Lava Cake", price: 99 },
      { itemId: 43, itemName: "Taco Mexicana Veg", price: 129 },
      { itemId: 44, itemName: "Classic Veg Pizza", price: 119 },
      { itemId: 45, itemName: "Pepsi", price: 60 },
    ],
  },
  {
    resId: 4,
    resName: "McDonald",
    address: "Mantri Mall, Bengaluru",
    rating: 4.2,
    menu: [
      { itemId: 46, itemName: "McAloo Tikki", price: 59 },
      { itemId: 47, itemName: "McSpicy Paneer", price: 170 },
      { itemId: 48, itemName: "Fries", price: 99 },
      { itemId: 49, itemName: "Veg Maharaja Mac", price: 215 },
      { itemId: 50, itemName: "Strawberry Shake", price: 95 },
      { itemId: 51, itemName: "McFlurry", price: 100 },
      { itemId: 52, itemName: "Cheesy Italian Burger", price: 189 },
      { itemId: 53, itemName: "Chicken Nuggets", price: 140 },
      { itemId: 54, itemName: "Filet-O-Fish", price: 175 },
      { itemId: 55, itemName: "McEgg", price: 49 },
      { itemId: 56, itemName: "Coke Float", price: 70 },
      { itemId: 57, itemName: "Veg McPuff", price: 44 },
      { itemId: 58, itemName: "Chicken Kebab Burger", price: 110 },
      { itemId: 59, itemName: "Masala Wedges", price: 89 },
      { itemId: 60, itemName: "Vanilla Soft Serve", price: 39 },
    ],
  },
  {
    resId: 5,
    resName: "Burger King",
    address: "Forum Mall, Koramangala",
    rating: 4.1,
    menu: [
      { itemId: 61, itemName: "Whopper", price: 190 },
      { itemId: 62, itemName: "Veg Crunchy", price: 70 },
      { itemId: 63, itemName: "Chocolate Shake", price: 110 },
      { itemId: 64, itemName: "Chicken Fries", price: 99 },
      { itemId: 65, itemName: "Crispy Veg Burger", price: 79 },
      { itemId: 66, itemName: "Onion Rings", price: 79 },
      { itemId: 67, itemName: "Fiery Chicken Burger", price: 149 },
      { itemId: 68, itemName: "Veggie Strips", price: 60 },
      { itemId: 69, itemName: "Paneer King Burger", price: 135 },
      { itemId: 70, itemName: "Fries", price: 79 },
      { itemId: 71, itemName: "Peri Peri Fries", price: 89 },
      { itemId: 72, itemName: "King Egg Burger", price: 55 },
      { itemId: 73, itemName: "Chicken Whopper", price: 220 },
      { itemId: 74, itemName: "Coke", price: 49 },
      { itemId: 75, itemName: "Soft Serve Cone", price: 39 },
    ],
  },
  {
    resId: 6,
    resName: "Pizza Hut",
    address: "BTM Layout, Bengaluru",
    rating: 3.9,
    menu: [
      { itemId: 76, itemName: "Veggie Supreme", price: 320 },
      { itemId: 77, itemName: "Cheese Garlic Bread", price: 110 },
      { itemId: 78, itemName: "Stuffed Crust Pizza", price: 400 },
      { itemId: 79, itemName: "Paneer Tikka Masala Pizza", price: 350 },
      { itemId: 80, itemName: "Tandoori Paneer Pizza", price: 360 },
      { itemId: 81, itemName: "Country Feast", price: 330 },
      { itemId: 82, itemName: "Chicken Tandoori Pizza", price: 375 },
      { itemId: 83, itemName: "Veggie Roll", price: 70 },
      { itemId: 84, itemName: "Choco Volcano", price: 75 },
      { itemId: 85, itemName: "Classic Corn Pizza", price: 210 },
      { itemId: 86, itemName: "Mushroom Delight Pizza", price: 295 },
      { itemId: 87, itemName: "Paneer Pocket", price: 80 },
      { itemId: 88, itemName: "Tomato Basil Pizza", price: 220 },
      { itemId: 89, itemName: "Cold Drink", price: 60 },
      { itemId: 90, itemName: "Pepperoni Pizza", price: 410 },
    ],
  },
  {
    resId: 7,
    resName: "Subway",
    address: "Indiranagar, Bengaluru",
    rating: 4.0,
    menu: [
      { itemId: 91, itemName: "Veggie Delight", price: 150 },
      { itemId: 92, itemName: "Paneer Tikka Sub", price: 170 },
      { itemId: 93, itemName: "Cookies", price: 60 },
      { itemId: 94, itemName: "Aloo Patty Sub", price: 150 },
      { itemId: 95, itemName: "Choco Chip Cookie", price: 55 },
      { itemId: 96, itemName: "Corn & Peas Sub", price: 147 },
      { itemId: 97, itemName: "Chatpata Chana Sub", price: 150 },
      { itemId: 98, itemName: "Veg Shammi Sub", price: 160 },
      { itemId: 99, itemName: "Subway Club", price: 195 },
      { itemId: 100, itemName: "Spicy Italian Sub", price: 210 },
      { itemId: 101, itemName: "Chicken Teriyaki Sub", price: 210 },
      { itemId: 102, itemName: "Egg & Cheese Sub", price: 120 },
      { itemId: 103, itemName: "Roasted Chicken Sub", price: 195 },
      { itemId: 104, itemName: "Veggie Patty", price: 155 },
      { itemId: 105, itemName: "Cold Coffee", price: 110 },
    ],
  },
  {
    resId: 8,
    resName: "Haldiram's",
    address: "Commercial Street, Bengaluru",
    rating: 4.2,
    menu: [
      { itemId: 106, itemName: "Raj Kachori", price: 110 },
      { itemId: 107, itemName: "Chole Bhature", price: 130 },
      { itemId: 108, itemName: "Rasgulla", price: 50 },
      { itemId: 109, itemName: "Dhokla", price: 70 },
      { itemId: 110, itemName: "Samosa", price: 30 },
      { itemId: 111, itemName: "Aloo Tikki", price: 35 },
      { itemId: 112, itemName: "Kaju Katli", price: 125 },
      { itemId: 113, itemName: "Bhujia", price: 45 },
      { itemId: 114, itemName: "Khasta Kachori", price: 40 },
      { itemId: 115, itemName: "Bhature Chole", price: 130 },
      { itemId: 116, itemName: "Paneer Pakora", price: 65 },
      { itemId: 117, itemName: "Jalebi", price: 60 },
      { itemId: 118, itemName: "Pav Bhaji", price: 110 },
      { itemId: 119, itemName: "Gulab Jamun", price: 45 },
      { itemId: 120, itemName: "Boondi Ladoo", price: 30 },
    ],
  },
  {
    resId: 9,
    resName: "Bikanervala",
    address: "Jayanagar, Bengaluru",
    rating: 4.3,
    menu: [
      { itemId: 121, itemName: "Pav Bhaji", price: 120 },
      { itemId: 122, itemName: "Thali", price: 250 },
      { itemId: 123, itemName: "Gulab Jamun", price: 60 },
      { itemId: 124, itemName: "Kesar Jalebi", price: 75 },
      { itemId: 125, itemName: "Kachori", price: 40 },
      { itemId: 126, itemName: "Dhokla", price: 55 },
      { itemId: 127, itemName: "Paneer Tikka", price: 135 },
      { itemId: 128, itemName: "Rasmalai", price: 70 },
      { itemId: 129, itemName: "Aloo Tikki Chaat", price: 65 },
      { itemId: 130, itemName: "Vegetable Cutlet", price: 50 },
      { itemId: 131, itemName: "Masala Dosa", price: 90 },
      { itemId: 132, itemName: "Sev Puri", price: 45 },
      { itemId: 133, itemName: "Rajma Chawal", price: 95 },
      { itemId: 134, itemName: "Boondi Raita", price: 40 },
      { itemId: 135, itemName: "Rabri", price: 80 },
    ],
  },
  {
    resId: 10,
    resName: "Behrouz Biryani",
    address: "Koramangala, Bengaluru",
    rating: 4.5,
    menu: [
      { itemId: 136, itemName: "Murg Biryani", price: 350 },
      { itemId: 137, itemName: "Paneer Biryani", price: 320 },
      { itemId: 138, itemName: "Raita", price: 60 },
      { itemId: 139, itemName: "Murgh Seekh Kebab", price: 180 },
      { itemId: 140, itemName: "Gulab Jamun (2pcs)", price: 70 },
      { itemId: 141, itemName: "Subz Biryani", price: 290 },
      { itemId: 142, itemName: "Chicken Tikka Biryani", price: 370 },
      { itemId: 143, itemName: "Egg Biryani", price: 250 },
      { itemId: 144, itemName: "Mutton Biryani", price: 430 },
      { itemId: 145, itemName: "Makhani Gravy", price: 80 },
      { itemId: 146, itemName: "Lucknowi Dum Biryani", price: 360 },
      { itemId: 147, itemName: "Paratha", price: 49 },
      { itemId: 148, itemName: "Paneer 65", price: 160 },
      { itemId: 149, itemName: "Tandoori Chicken", price: 220 },
      { itemId: 150, itemName: "Methi Malai Biryani", price: 285 },
    ],
  },
  {
    resId: 11,
    resName: "Faasos",
    address: "HSR Layout, Bengaluru",
    rating: 4.0,
    menu: [
      { itemId: 151, itemName: "Cheese Roll", price: 120 },
      { itemId: 152, itemName: "Chicken Wrap", price: 140 },
      { itemId: 153, itemName: "Egg Roll", price: 90 },
      { itemId: 154, itemName: "Veggie Falafel Roll", price: 130 },
      { itemId: 155, itemName: "Paneer Tikka Wrap", price: 150 },
      { itemId: 156, itemName: "Double Egg Roll", price: 110 },
      { itemId: 157, itemName: "Chicken Seekh Roll", price: 160 },
      { itemId: 158, itemName: "Veggie Delight Roll", price: 90 },
      { itemId: 159, itemName: "Chicken Bhuna Wrap", price: 155 },
      { itemId: 160, itemName: "Mutton Seekh Roll", price: 180 },
      { itemId: 161, itemName: "Chicken Mayo Roll", price: 145 },
      { itemId: 162, itemName: "Paneer Masala Roll", price: 135 },
      { itemId: 163, itemName: "Veg Schezwan Roll", price: 120 },
      { itemId: 164, itemName: "Kathi Paneer Roll", price: 130 },
      { itemId: 165, itemName: "Harabhara Kabab Wrap", price: 120 },
    ],
  },
  {
    resId: 12,
    resName: "Rolls Mania",
    address: "Malleshwaram, Bengaluru",
    rating: 4.1,
    menu: [
      { itemId: 166, itemName: "Double Egg Roll", price: 100 },
      { itemId: 167, itemName: "Chicken Seekh Roll", price: 160 },
      { itemId: 168, itemName: "Veggie Delight Roll", price: 90 },
      { itemId: 169, itemName: "Chicken Tikka Roll", price: 170 },
      { itemId: 170, itemName: "Paneer Mughlai Roll", price: 120 },
      { itemId: 171, itemName: "Aloo Cheese Roll", price: 80 },
      { itemId: 172, itemName: "Paneer Bhurji Roll", price: 110 },
      { itemId: 173, itemName: "Mutton Bhuna Roll", price: 180 },
      { itemId: 174, itemName: "Egg Chicken Roll", price: 125 },
      { itemId: 175, itemName: "Schezwan Veg Roll", price: 90 },
      { itemId: 176, itemName: "Corn and Cheese Roll", price: 85 },
      { itemId: 177, itemName: "Veg Kabab Roll", price: 85 },
      { itemId: 178, itemName: "Egg Cheese Roll", price: 105 },
      { itemId: 179, itemName: "Chicken Masala Roll", price: 150 },
      { itemId: 180, itemName: "Mushroom Roll", price: 110 },
    ],
  },
  {
    resId: 13,
    resName: "Giani's",
    address: "MG Road, Bengaluru",
    rating: 4.3,
    menu: [
      { itemId: 181, itemName: "Chocolate Ice Cream", price: 80 },
      { itemId: 182, itemName: "Kulfi Falooda", price: 120 },
      { itemId: 183, itemName: "Belgian Chocolate Sundae", price: 150 },
      { itemId: 184, itemName: "Vanilla Ice Cream", price: 70 },
      { itemId: 185, itemName: "Raspberry Sorbet", price: 90 },
      { itemId: 186, itemName: "Mango Scoop", price: 65 },
      { itemId: 187, itemName: "Kesar Pista Kulfi", price: 75 },
      { itemId: 188, itemName: "Choco Brownie Fudge", price: 135 },
      { itemId: 189, itemName: "Butterscotch Ice Cream", price: 80 },
      { itemId: 190, itemName: "Strawberry Sundae", price: 120 },
      { itemId: 191, itemName: "Coffee Fudge", price: 95 },
      { itemId: 192, itemName: "Fruit & Nut", price: 105 },
      { itemId: 193, itemName: "Oreo Sundae", price: 130 },
      { itemId: 194, itemName: "Almond Crunch", price: 110 },
      { itemId: 195, itemName: "Caramel Swirl", price: 115 },
    ],
  },
  {
    resId: 14,
    resName: "The Belgian Waffle",
    address: "Church Street, Bengaluru",
    rating: 4.4,
    menu: [
      { itemId: 196, itemName: "Strawberry Cream Waffle", price: 160 },
      { itemId: 197, itemName: "Chocolate Overload Waffle", price: 180 },
      { itemId: 198, itemName: "Nutella Waffle", price: 170 },
      { itemId: 199, itemName: "Blueberry Cream Waffle", price: 170 },
      { itemId: 200, itemName: "Coffee Waffle", price: 165 },
      { itemId: 201, itemName: "Banana Caramel Waffle", price: 180 },
      { itemId: 202, itemName: "Crunchy Kitkat Waffle", price: 175 },
      { itemId: 203, itemName: "Black Forest Waffle", price: 190 },
      { itemId: 204, itemName: "Vanilla Dream Waffle", price: 150 },
      { itemId: 205, itemName: "Double Chocolate Chip Waffle", price: 180 },
      { itemId: 206, itemName: "Red Velvet Waffle", price: 200 },
      { itemId: 207, itemName: "Classic Butter Waffle", price: 145 },
      { itemId: 208, itemName: "Maple Syrup Waffle", price: 160 },
      { itemId: 209, itemName: "Mango Waffle", price: 170 },
      { itemId: 210, itemName: "Oreo Cookie Waffle", price: 185 },
    ],
  },
  {
    resId: 15,
    resName: "Chaayos",
    address: "Koramangala, Bengaluru",
    rating: 4.2,
    menu: [
      { itemId: 211, itemName: "Desi Chai", price: 70 },
      { itemId: 212, itemName: "Samosa Matar", price: 90 },
      { itemId: 213, itemName: "Kulhad Pav Bhaji", price: 130 },
      { itemId: 214, itemName: "Vada Pav", price: 60 },
      { itemId: 215, itemName: "Masala Chai", price: 75 },
      { itemId: 216, itemName: "Paneer Sandwich", price: 110 },
      { itemId: 217, itemName: "Chilled Aam Panna", price: 85 },
      { itemId: 218, itemName: "Poha", price: 65 },
      { itemId: 219, itemName: "Chilli Cheese Toast", price: 95 },
      { itemId: 220, itemName: "Chocolate Shake", price: 90 },
      { itemId: 221, itemName: "Sabudana Vada", price: 85 },
      { itemId: 222, itemName: "Kulhad Wali Chai", price: 60 },
      { itemId: 223, itemName: "Matka Kulfi", price: 80 },
      { itemId: 224, itemName: "Classic Cold Coffee", price: 95 },
      { itemId: 225, itemName: "Bun Maska", price: 60 },
    ],
  },
  {
    resId: 16,
    resName: "Cafe Coffee Day",
    address: "BTM Layout, Bengaluru",
    rating: 4.0,
    menu: [
      { itemId: 226, itemName: "Cappuccino", price: 150 },
      { itemId: 227, itemName: "Cold Coffee", price: 130 },
      { itemId: 228, itemName: "Garlic Bread", price: 100 },
      { itemId: 229, itemName: "Cafe Latte", price: 155 },
      { itemId: 230, itemName: "Muffin", price: 80 },
      { itemId: 231, itemName: "Espresso", price: 120 },
      { itemId: 232, itemName: "Irish Coffee", price: 150 },
      { itemId: 233, itemName: "Choco Frappe", price: 140 },
      { itemId: 234, itemName: "Brownie", price: 90 },
      { itemId: 235, itemName: "Hot Chocolate", price: 130 },
      { itemId: 236, itemName: "Mocha", price: 140 },
      { itemId: 237, itemName: "Veg Club Sandwich", price: 120 },
      { itemId: 238, itemName: "Paneer Tikka Sandwich", price: 135 },
      { itemId: 239, itemName: "Cheese Croissant", price: 115 },
      { itemId: 240, itemName: "Lemon Iced Tea", price: 95 },
    ],
  },
  {
    resId: 17,
    resName: "Sweet Truth",
    address: "Indiranagar, Bengaluru",
    rating: 4.3,
    menu: [
      { itemId: 241, itemName: "Chocolate Cake", price: 150 },
      { itemId: 242, itemName: "Red Velvet", price: 180 },
      { itemId: 243, itemName: "Cheesecake", price: 190 },
      { itemId: 244, itemName: "Caramel Hazelnut Cake", price: 160 },
      { itemId: 245, itemName: "Tiramisu", price: 175 },
      { itemId: 246, itemName: "Brownie", price: 99 },
      { itemId: 247, itemName: "Black Forest Cake", price: 155 },
      { itemId: 248, itemName: "Nutty Butterscotch Cake", price: 150 },
      { itemId: 249, itemName: "Strawberry Mousse", price: 120 },
      { itemId: 250, itemName: "Dutch Truffle Cake", price: 175 },
      { itemId: 251, itemName: "Chocolate Truffle Pastry", price: 99 },
      { itemId: 252, itemName: "Raspberry Cheesecake", price: 195 },
      { itemId: 253, itemName: "Blueberry Cake", price: 175 },
      { itemId: 254, itemName: "Walnut Brownie", price: 105 },
      { itemId: 255, itemName: "Mango Cheesecake", price: 180 },
    ],
  },
  {
    resId: 18,
    resName: "Oven Story Pizza",
    address: "HSR Layout, Bengaluru",
    rating: 4.1,
    menu: [
      { itemId: 256, itemName: "Cheesy Margarita", price: 249 },
      { itemId: 257, itemName: "El Classico Paneer", price: 299 },
      { itemId: 258, itemName: "Spicy Peri Peri", price: 270 },
      { itemId: 259, itemName: "Veggie Loaded", price: 270 },
      { itemId: 260, itemName: "Paneer Supreme", price: 310 },
      { itemId: 261, itemName: "Firey Chicken", price: 325 },
      { itemId: 262, itemName: "Cheese Burst Pizza", price: 325 },
      { itemId: 263, itemName: "Chicken Tikka Pizza", price: 345 },
      { itemId: 264, itemName: "Classic Corn Pizza", price: 220 },
      { itemId: 265, itemName: "Farmfresh Delight", price: 270 },
      { itemId: 266, itemName: "Garlic Breadsticks", price: 110 },
      { itemId: 267, itemName: "Choco Lava Cake", price: 95 },
      { itemId: 268, itemName: "Veg Supreme Pizza", price: 299 },
      { itemId: 269, itemName: "Classic Loaded Pizza", price: 250 },
      { itemId: 270, itemName: "Stuffed Crust Pizza", price: 400 },
    ],
  },
  {
    resId: 19,
    resName: "LunchBox",
    address: "Jayanagar, Bengaluru",
    rating: 4.2,
    menu: [
      { itemId: 271, itemName: "Rajma Chawal", price: 150 },
      { itemId: 272, itemName: "Paneer Tikka Bowl", price: 180 },
      { itemId: 273, itemName: "Masala Dal Khichdi", price: 140 },
      { itemId: 274, itemName: "Aloo Paratha with Dahi", price: 120 },
      { itemId: 275, itemName: "Chole Pindi with Rice", price: 155 },
      { itemId: 276, itemName: "Dal Makhni Rice Bowl", price: 135 },
      { itemId: 277, itemName: "Mix Veg Curry Rice", price: 140 },
      { itemId: 278, itemName: "Homestyle Chicken Curry", price: 180 },
      { itemId: 279, itemName: "Egg Curry with Rice", price: 150 },
      { itemId: 280, itemName: "Paneer Butter Masala Rice", price: 160 },
      { itemId: 281, itemName: "Lemon Rice", price: 110 },
      { itemId: 282, itemName: "Curd Rice", price: 90 },
      { itemId: 283, itemName: "Poha Bowl", price: 95 },
      { itemId: 284, itemName: "Methi Aloo Rice", price: 125 },
      { itemId: 285, itemName: "Sabudana Khichdi", price: 120 },
    ],
  },
];

//here i used named export
